Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from graphviz import Digraph

dot = Digraph(comment='The Perceptron', node_attr={'color':'salmon', 'style':'filled'})

dot.attr('node')
dot.node('x1', 'Rooms')
dot.node('x2', 'Bedrooms')
dot.node('x3', 'Square Footage')
dot.node('neuron', 'node')
dot.node('output', 'Price Prediction')

dot.edge('x1', 'neuron', label = 'w1')
dot.edge('x2', 'neuron', label = 'w2')
dot.edge('x3', 'neuron', label = 'w3')
dot.edge('neuron', 'output')
# dot.edge('B', 'L', constraint='false')

dot.attr(label=r'\nBasic Perceptron on Housing Data')
dot
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgraphviz[39;00m [38;5;28;01mimport[39;00m Digraph
[1;32m      3[0m dot [38;5;241m=[39m Digraph(comment[38;5;241m=[39m[38;5;124m'[39m[38;5;124mThe Perceptron[39m[38;5;124m'[39m, node_attr[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mcolor[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124msalmon[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mstyle[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124mfilled[39m[38;5;124m'[39m})
[1;32m      5[0m dot[38;5;241m.[39mattr([38;5;124m'[39m[38;5;124mnode[39m[38;5;124m'[39m)

[0;31mModuleNotFoundError[0m: No module named 'graphviz'

